[build-system]
requires = ["setuptools >= 61.0", "setuptools_scm >= 8.0"]
build-backend = "setuptools.build_meta"
include-package-date = true

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
"osdag_gui.resources" = [
    "**/*.png", "**/*.PNG", "**/*.jpg", "**/*.JPG", "**/*.jpeg", "**/*.JPEG", "**/*.svg",
    "**/*.qss", "**/*.ttf", "**/*.qrc"
]

[project]
name = "osdag-gui"
dynamic = ["version"]
dependencies = ["PySide6", "navcube", "markdown", "osdag-core"]
requires-python = ">= 3.10,<3.13"
description = "Open steel design - graphical interface"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["steel design", "civil engineering", "engineering"]

[project.scripts]
osdag-gui = "osdag_gui.__main__:main"
